language: node_js
node_js:
- 12.14.0
script:
- npm run test
- npm run build
deploy:
  deploy: 
  provider: npm
  skip_cleanup: true
  email: greenrenge@gmail.com
  api_key:
    secure: O78ubYx4ubEbJ1hTGE3ikBDwpk+3pSRTmF/nh9IFz8yBCx/8+6ZsZed4zY4NcG1YDKQ8esl2cWPc0vxjAPonwRH7pMIXdGwIVE75n0AcXQ4piFjLAQK/94IG2/Ds1G7BIxK37GBsSN7n6JaEjaed1mlaVZrBoxUaSfuKU50oksnAPRgVJoT9rcztS1IEb0XHWE2kYt+BAAfUbRyHkff9ofncbhTYm8O8wezYiHAtgp9pEtr/UyGX/3lAgPx0VntDak83y16/bLu/uibufXjHuRKDKB+GBrZ+WWCeffuaIfLZ6qpB1MpU3nmAaS6chTngzYcw6LCPfC3jtKBx/mht5psPuxafP0FccuE5GikyqPoB7mraFsmP4Xfmj2+qyBAbparVt/OrppfjJCWL+lLIPx47tRWCXdhS9c2NfJXJLaiwsA6YlcS351raEZKj/WYQnHIvh9Q9c1/HnbnhI17oscfB8dRP34CZhkL/bvGujMLuw414qI5bUBXq5dV1v7GsLvSeSakmvW620y7IIkIH5yfa8srHSWQ6wat3cwzmqYM23JZntg2Yjez+BOIYnfj5mjOsJrdnJxgP7z4esgNBkw7s7BQBwEQ2mbxZYE0m8bDwJm910OV0CQga0VwPyItCIc0ZjUqxc/x1SmK9Nf/DyCdyRDJ/25f7/b7lk0F1Qd0=
  on:
    tags: true
